name: publish to nuget and github
on:
  push:
    branches:
      - main # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: '5.x'
          
      - name: Cache
        uses: actions/cache@v2.1.4
        with:  
          path: ./*.nupkg
          key: ${{secrets.NUGET_API_KEY}}
          
      - name: Nuget Pack
        run: nuget pack ./pylonLibs.nuspec
        
      - name: Nuget.org Push
        run: nuget push *.nupkg -Source ${{secrets.NUGET_ORG_SOURCE}} -ApiKey ${{secrets.NUGET_API_KEY}} -Timeout ${{secrets.NUGET_TIMEOUT}}
      
      - name: Github Push
        run: nuget push *.nupkg -Source ${{secrets.NUGET_GITHUB_SOURCE}} -ApiKey ${{secrets.G_NUGET_API_KEY}} -Timeout ${{secrets.NUGET_TIMEOUT}}
